-- CREATE DATABASE "supermercado_rest";
-- CREATE DATABASE "supermercado_soap";
-- CREATE DATABASE "indec";

-- CREACION BASE DE DATOS INDEC
CREATE DATABASE "db_indec";
-- CREACION BASE DE DATOS SUPERMERCADO REST A
CREATE DATABASE "db_supermercado_rest_a";
-- DROP DATABASE IF EXISTS db_supermercado_rest_a;
-- CREACION BASE DE DATOS SUPERMERCADO REST B
CREATE DATABASE "db_supermercado_rest_b";
-- CREACION BASE DE DATOS SUPERMERCADO SOAP A
CREATE DATABASE "db_supermercado_soap_a";
-- CREACION BASE DE DATOS SUPERMERCADO SOAP B
CREATE DATABASE "db_supermercado_soap_b";
